apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: ice-tkgi-resources
  annotations:
    kapp.k14s.io/update-strategy: always-replace
spec:
  portal:
    registration:
      type: anonymous
  workshops:
  - name: ice-tkgi-resources
    capacity: 5 
    expires: 60m
    orphaned: 5m
