apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: ice-tkgi-resources
spec:
  portal:
    registration:
      type: anonymous
  workshops:
  - name: ice-tkgi-resources
    capacity: 1
    expires: 60m
    orphaned: 5m
